In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from torch.utils.data import Dataset 
from torch.utils.data import DataLoader

In [2]:
train_data = pd.read_csv('WDBC_Scaled_Train.csv')
validation_data = pd.read_csv('WDBC_Scaled_Validation.csv')
test_data = pd.read_csv('WDBC_Scaled_Test.csv')

In [3]:
X_train = train_data.iloc[:, 1:].values
y_train = train_data.iloc[:, 0].values
X_val = validation_data.iloc[:, 1:].values
y_val = validation_data.iloc[:, 0].values
X_test = test_data.iloc[:, 1:].values
y_test = test_data.iloc[:, 0].values


X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_val = torch.tensor(X_val, dtype=torch.float32)
y_val = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

In [20]:
   ####SINGLE LAYTER(10)
model1 = nn.Sequential(
    nn.Linear(30, 10),
    nn.Sigmoid(),
    nn.Linear(10, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model1.parameters(), lr=0.01)

with torch.no_grad():
    y_val_pred = model1(X_val)
    y_test_pred = model1(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[ 6 66]
 [ 0 42]]
Accuracy: 0.4211, Precision: 0.3889, Recall: 1.0000, F1-score: 0.5600


In [19]:
   ####SINGLE LAYTER(100)
model2 = nn.Sequential(
    nn.Linear(30, 100),
    nn.Sigmoid(),
    nn.Linear(100, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model2.parameters(), lr=0.01)

with torch.no_grad():
    y_val_pred = model2(X_val)
    y_test_pred = model2(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[ 0 72]
 [ 0 42]]
Accuracy: 0.3684, Precision: 0.3684, Recall: 1.0000, F1-score: 0.5385


In [14]:
   ####SINGLE LAYTER(64)
model3 = nn.Sequential(
    nn.Linear(30, 64),
    nn.Sigmoid(),
    nn.Linear(64, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model3.parameters(), lr=0.01)

with torch.no_grad():
    y_val_pred = model3(X_val)
    y_test_pred = model3(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[72  0]
 [35  7]]
Accuracy: 0.6930, Precision: 1.0000, Recall: 0.1667, F1-score: 0.2857


In [13]:
   ####SINGLE LAYTER(512)
model4 = nn.Sequential(
    nn.Linear(30, 512),
    nn.Sigmoid(),
    nn.Linear(512, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model4.parameters(), lr=0.01)

with torch.no_grad():
    y_val_pred = model4(X_val)
    y_test_pred = model4(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[71  1]
 [42  0]]
Accuracy: 0.6228, Precision: 0.0000, Recall: 0.0000, F1-score: 0.0000


In [21]:
#FOR TWOLAYER (128,32)
model5 = nn.Sequential(
    nn.Linear(30, 128),
    nn.Sigmoid(),
    nn.Linear(128, 32),
    nn.Sigmoid(),
    nn.Linear(32, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model5.parameters(), lr=0.01)
with torch.no_grad():
    y_val_pred = model5(X_val)
    y_test_pred = model5(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[ 0 72]
 [ 0 42]]
Accuracy: 0.3684, Precision: 0.3684, Recall: 1.0000, F1-score: 0.5385


In [22]:
 #FOR TWOLAYER (64,16)
model6 = nn.Sequential(
    nn.Linear(30, 64),
    nn.Sigmoid(),
    nn.Linear(64, 16),
    nn.Sigmoid(),
    nn.Linear(16, 1),
    nn.Sigmoid()
)
criterion = nn.MSELoss()
optimizer = optim.SGD(model6.parameters(), lr=0.01)
with torch.no_grad():
    y_val_pred = model6(X_val)
    y_test_pred = model6(X_test)


y_val_pred = (y_val_pred >= 0.5).float()
y_test_pred = (y_test_pred >= 0.5).float()


conf_matrix = confusion_matrix(y_test.numpy(), y_test_pred.numpy())
accuracy = accuracy_score(y_test.numpy(), y_test_pred.numpy())
precision = precision_score(y_test.numpy(), y_test_pred.numpy())
recall = recall_score(y_test.numpy(), y_test_pred.numpy())
f1 = f1_score(y_test.numpy(), y_test_pred.numpy())


print("Confusion Matrix:\n", conf_matrix)
print(f"Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

Confusion Matrix:
 [[ 0 72]
 [ 0 42]]
Accuracy: 0.3684, Precision: 0.3684, Recall: 1.0000, F1-score: 0.5385
